'use strict';
const $=id=>document.getElementById(id),KEY='schneckenchecker-v1';let state=Engine.fresh(),selected=null,last=performance.now(),noticeTimer;
try{const saved=localStorage.getItem(KEY);if(saved){const parsed=JSON.parse(saved);if(Engine.valid(parsed)){state=parsed;state.upgrades??=[];for(const type of Object.keys(TYPES))state.levels[type]??=0;}else notify('Gespeicherter Spielstand ist ungültig. Neues Spiel gestartet.');}}catch{notify('Der Spielstand konnte nicht geladen werden.');}
const fmt=n=>Number.isFinite(n)?new Intl.NumberFormat('de-DE',{maximumFractionDigits:n>=1e6?2:2,notation:n>=1e6?'compact':'standard'}).format(n):'Maximum';
function notify(message){$('notice').textContent=message;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('notice').textContent='',3500);}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));$('save').textContent='Lokal gespeichert';}catch{$('save').textContent='Speichern nicht möglich';}}
function settle(){const now=performance.now();state.cells+=Engine.total(state)*Math.max(0,(now-last)/1000);last=now;}
function action(fn){settle();try{fn();save();render();}catch(e){notify(e.message);}}
function buy(type){action(()=>{const n=Engine.buy(state,type);selected=n.id;notify(TYPES[type].name+' gekauft. Wähle ein Feld.');});}
function cellClick(pos){action(()=>{const occupant=state.snails.find(n=>n.position===pos);if(selected!==null){const n=state.snails.find(x=>x.id===selected);if(n.position===pos)selected=null;else{Engine.move(state,selected,pos);selected=null;}}else if(occupant)selected=occupant.id;else notify('Wähle zuerst eine Schnecke aus dem Inventar.');});}
function icon(type){return '<span aria-hidden="true" class="snail '+type+'">🐌</span>';}
function shopEffect(type){
 if(type==='glue'){const diagonal=Engine.hasUpgrade(state,'glueDiagonal')?' Diagonale Nachbarn: +⅙.':'';return (Engine.hasUpgrade(state,'glueStack')?'Orthogonale Nachbarn: ×4/3 je Klebenachbar, multiplikativ.':'Orthogonale Nachbarn: +⅓, ohne Stapelung.')+diagonal;}
 if(type==='space')return Engine.hasUpgrade(state,'spaceDiagonal')?'Eigene Produktion × (1 + freie orthogonale und diagonale Nachbarfelder).':TYPES[type].effect;
 if(type==='line')return Engine.hasUpgrade(state,'lineMultiply')?'Gleiche Reihe oder Spalte: ×1,25 je Linienschnecke, multiplikativ.':Engine.hasUpgrade(state,'lineAdd')?'Gleiche Reihe oder Spalte: +25 % je Linienschnecke, additiv.':TYPES[type].effect;
 if(type==='amplifier')return Engine.hasUpgrade(state,'amplifierTurbo')?'Normale Schnecken: +50 % je Verstärkerschnecke, verstärkt um 5 % pro aktiver Turboschnecke.':TYPES[type].effect;
 if(type==='turbo'&&Engine.hasUpgrade(state,'turboTeam'))return '+5 % Produktion pro aktiver normaler Schnecke.';
 return TYPES[type].effect;
}
function render(){const chosen=state.snails.find(n=>n.id===selected);$('instruction').textContent=chosen?'Zielfeld anklicken · belegte Felder tauschen die Schnecken.':'Schnecke anklicken, um sie zu versetzen.';
$('board').innerHTML=Array.from({length:25},(_,pos)=>{const n=state.snails.find(x=>x.position===pos),coord=String.fromCharCode(65+pos%5)+(Math.floor(pos/5)+1),boost=n&&Engine.boosted(state,n);return '<button class="tile '+(boost?'boosted ':'')+(n?.id===selected?'selected':'')+'" data-glue-bonus="'+(boost?'+'+fmt((Engine.glueFactor(state,n)-1)*100)+'%':'')+'" data-cell="'+pos+'" aria-label="'+coord+(n?' '+TYPES[n.type].name+', '+fmt(Engine.production(state,n))+' Zellen pro Sekunde':' leer')+'"><span class="coord">'+coord+'</span>'+(n?icon(n.type)+'<span class="tile-rate">'+fmt(Engine.production(state,n))+'/s</span>':'<span class="empty">+</span>')+'</button>';}).join('');
$('shop').innerHTML=Object.entries(TYPES).map(([type,t])=>'<article class="shop-card '+type+'"><div class="shop-top"><div class="shop-icon">'+icon(type)+'</div><div><h3>'+t.name+'</h3><p>'+state.snails.filter(x=>x.type===type).length+' im Besitz</p></div></div><p class="effect">'+shopEffect(type)+'</p><div class="shop-bottom"><span class="base">'+Engine.purchaseBase(state,type)+' Zellen / Sek.</span><button class="action" data-buy="'+type+'"></button></div></article>').join('');
$('selection').innerHTML=chosen?'<div><b>'+TYPES[chosen.type].name+' <span class="muted">#'+chosen.id+'</span></b><p class="muted">Basis '+fmt(chosen.base)+'/s'+(chosen.position!==null?' · aktuell '+fmt(Engine.production(state,chosen))+'/s':' · im Inventar')+'</p></div><button class="action secondary" id="selection-action">'+(chosen.position!==null?'Ins Inventar':'Abwählen')+'</button>':'<div><b>Platz für deine nächste Idee.</b><p class="muted">Kaufe eine Schnecke und setze sie auf ein freies Feld.</p></div>';
if(chosen)$('selection-action').onclick=()=>action(()=>{if(chosen.position!==null)Engine.move(state,chosen.id,null);selected=null;});
const inventory=state.snails.filter(n=>n.position===null);$('inventory-count').textContent=inventory.length;$('inventory').innerHTML=inventory.length?inventory.map(n=>'<article class="inventory-card '+(n.id===selected?'selected':'')+'"><p>'+icon(n.type)+' '+TYPES[n.type].name+' <small>#'+n.id+'</small><br><small>Basis '+fmt(n.base)+'/s · '+shopEffect(n.type)+'</small></p><div class="inventory-actions"><button class="action" data-select="'+n.id+'">'+(n.id===selected?'Ausgewählt':'Platzieren')+'</button><button class="action secondary" data-sell="'+n.id+'">Verkaufen · '+fmt(Engine.sellPrice(state,n))+'</button></div></article>').join(''):'<div class="inventory-empty">Hier ist noch alles frei. Gekaufte Schnecken warten hier auf ihren Einsatz.</div>';
$('upgrades').innerHTML=Object.entries(UPGRADES).map(([id,u])=>'<article class="upgrade-card '+(Engine.hasUpgrade(state,id)?'owned':'')+'"><h3>'+u.name+'</h3><p>'+u.description+'</p><button class="action" data-upgrade="'+id+'"></button></article>').join('');
$('upgrade-count').textContent=(state.upgrades??[]).length+' / '+Object.keys(UPGRADES).length;
$('glue-legend').textContent=(Engine.hasUpgrade(state,'glueStack')?'×4/3 orthogonal · multiplikativ':'+⅓ orthogonal · nicht stapelbar')+(Engine.hasUpgrade(state,'glueDiagonal')?' · +⅙ diagonal':'');
$('active').textContent=state.snails.length-inventory.length;$('rate').textContent=fmt(Engine.total(state));updateNumbers();}
function updateNumbers(){document.querySelectorAll('[data-upgrade]').forEach(b=>{const id=b.dataset.upgrade,u=UPGRADES[id],owned=Engine.hasUpgrade(state,id);b.disabled=owned||state.cells<u.cost;b.textContent=owned?'✓ Gekauft':'Kaufen · '+fmt(u.cost)+' Zellen';b.setAttribute('aria-label',u.name+(owned?' bereits gekauft':' kaufen für '+fmt(u.cost)+' Zellen'));});$('cells').textContent=fmt(state.cells);document.querySelectorAll('[data-buy]').forEach(b=>{let p=Engine.price(b.dataset.buy,state.levels[b.dataset.buy]);b.disabled=!Number.isFinite(p)||state.cells<p;b.textContent='Kaufen · '+fmt(p);b.setAttribute('aria-label',TYPES[b.dataset.buy].name+' kaufen für '+fmt(p)+' Zellen');});}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.cell!==undefined)cellClick(Number(b.dataset.cell));if(b.dataset.buy)buy(b.dataset.buy);if(b.dataset.upgrade)action(()=>{Engine.buyUpgrade(state,b.dataset.upgrade);notify(UPGRADES[b.dataset.upgrade].name+' ist jetzt aktiv.');});if(b.dataset.select)action(()=>selected=Number(b.dataset.select));if(b.dataset.sell)action(()=>{let id=Number(b.dataset.sell),p=Engine.sell(state,id);if(selected===id)selected=null;notify('Verkauft für '+fmt(p)+' Zellen. Kaufpreis gesenkt.');});});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){selected=null;render();}});
setInterval(()=>{settle();updateNumbers();},100);setInterval(save,5000);document.addEventListener('visibilitychange',()=>{settle();save();});window.addEventListener('pagehide',()=>{settle();save();});render();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_snail_game',description:'Liest Zellen, Produktion, Kaufpreise und alle einzelnen Schnecken.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(){return {cells:state.cells,upgrades:[...(state.upgrades??[])],production:Engine.total(state),snails:state.snails.map(n=>({...n})),prices:Object.fromEntries(Object.keys(TYPES).map(t=>[t,Engine.price(t,state.levels[t])]))};}})).catch(()=>{});}catch{}}
